import './globals.scss'
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import {ReactNode} from "react";
import Header from "@/components/Header/Header";

const poppins = Poppins({weight: ['100', '300', '400', '700'], subsets: ['latin-ext']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Header/>
                <div className={"px-12"}>
                    {children}
                </div>
            </body>
        </html>
    )
}
